gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat

This is an auto-generated PR with an updated gradle version

project: Update gradle wrapper

---

blastfurnance/blastfurnance.gradle.kts
blastfurnance/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnacePlugin.java
customcursor/customcursor.gradle.kts
customcursor/src/main/java/net/runelite/client/plugins/customcursor/CustomCursorPlugin.java
stealingartefacts/src/main/java/net/runelite/client/plugins/stealingartefacts/StealingArtefactsPlugin.java
stealingartefacts/stealingartefacts.gradle.kts
woodcutting/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingPlugin.java
woodcutting/woodcutting.gradle.kts

plugins: Fix blastfurnance, customcursor, stealingartefacts and

---

effecttimers/effecttimers.gradle.kts
effecttimers/src/main/java/net/runelite/client/plugins/effecttimers/PlayerSpellEffect.java

effecttimers: fix SOTD
apparently blue cant tell the difference between 1228 and 1288 💃

effecttimers: fix SOTD

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

MES: hide restore for magma/tanz helms.

MES: hide restore for magma/tanz helms.

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

mes: fix tanz/magma

---

buildSrc/src/main/kotlin/Dependencies.kt
gpu/gpu.gradle.kts
gpu/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
tmorph/src/main/java/net/runelite/client/plugins/tmorph/TMorphConfig.java
tmorph/src/main/java/net/runelite/client/plugins/tmorph/TmorphSet.java
tmorph/src/main/java/net/runelite/client/plugins/tmorph/ui/TPanel.java
tmorph/tmorph.gradle.kts

upstream: merge

---

gpu/gpu.gradle.kts
gpu/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java

gpu: bush did it

---

gpu/gpu.gradle.kts
gpu/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java

gpu: ok, but, like, why?

---

loottracker/loottracker.gradle.kts
loottracker/src/main/java/net/runelite/client/plugins/loottracker/Pet.java

lottracker: add pets

---

loottracker/loottracker.gradle.kts
loottracker/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

loottracker: fix clue scroll crash

---

statusorbs/src/main/java/net/runelite/client/plugins/statusorbs/StatusOrbsConfig.java
statusorbs/src/main/java/net/runelite/client/plugins/statusorbs/StatusOrbsPlugin.java
statusorbs/statusorbs.gradle.kts

statusorbs: show spec regen when full spec

statusorbs: show spec regen when full spec

---

statusorbs/src/main/java/net/runelite/client/plugins/statusorbs/StatusOrbsConfig.java
statusorbs/src/main/java/net/runelite/client/plugins/statusorbs/StatusOrbsPlugin.java
statusorbs/statusorbs.gradle.kts

statusorbs: fix config issue

---

loottracker/loottracker.gradle.kts
loottracker/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

loottracker: fix HA price in panel
fixes #69

loottracker: fix HA price in panel

---

entityhider/entityhider.gradle.kts
entityhider/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java
entityhider/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java

entityhider: compliance

---

buildSrc/src/main/kotlin/Dependencies.kt

version: update

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

mes: fix custom swaps

---

runecraft/runecraft.gradle.kts
runecraft/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java

runecrafting: remove unused config option

runecrafting: remove unused config option

---

banktags/banktags.gradle.kts
banktags/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java

Requires open-osrs/runelite#2399

banktags: fix callback name

---

thieving/src/main/java/net/runelite/client/plugins/thieving/ThievingPlugin.java
thieving/thieving.gradle.kts

thieving: Ardy knight support

---

opponentinfo/opponentinfo.gradle.kts
opponentinfo/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoConfig.java
opponentinfo/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java

adds back 
https://github.com/runelite/runelite/commit/34f94e973c18627a3d7f20faf8160647b87c09c9

oppinfo: add missing commit

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

redid a bunch of stuff
added a bunch of stuff

mes: updates

---

tickcounter/src/main/java/net/runelite/client/plugins/combatcounter/CombatCounter.java
tickcounter/tickcounter.gradle.kts

tickcounter: add swiftblade

---

experiencedrop/experiencedrop.gradle.kts
experiencedrop/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java

xpdrop: fix tick timer

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

mes: update gembag

---

herbiboar/herbiboar.gradle.kts
herbiboar/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarPlugin.java

herbi: add @Extension tag

---

buildSrc/src/main/kotlin/Dependencies.kt

project: version bump

---

worldmap/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java
worldmap/worldmap.gradle.kts

worldmap: upstream

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

mes: fix left click drop fish

---

herbiboar/herbiboar.gradle.kts
herbiboar/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarPlugin.java

herbi: add plugintype

---

dpscounter/dpscounter.gradle.kts
dpscounter/src/main/java/net/runelite/client/plugins/dpscounter/DpsCounterPlugin.java

dpscounter: add plugintype

---

loottracker/loottracker.gradle.kts
loottracker/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

loottracker: upstream

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
runecraft/runecraft.gradle.kts
runecraft/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java
runecraft/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java

project: move esspouch mes

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java

menuentryswapperconfig: section

---

devtools/devtools.gradle.kts
devtools/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java

devtools: add player IDX

---

grounditems/grounditems.gradle.kts
grounditems/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java

grounditems: revert

---

objectindicators/objectindicators.gradle.kts
objectindicators/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java

objectremover: fix

---

grounditems/grounditems.gradle.kts
grounditems/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java

grounditems: fix + upstream

---

grounditems/grounditems.gradle.kts
grounditems/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java

upstream: ground items

---

banktags/banktags.gradle.kts
banktags/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java

banktags: fix menu entry

---

thieving/src/main/java/net/runelite/client/plugins/thieving/ThievingPlugin.java
thieving/thieving.gradle.kts

thievingplugin: add elves

---

statusorbs/src/main/java/net/runelite/client/plugins/statusorbs/StatusOrbsConfig.java
statusorbs/src/main/java/net/runelite/client/plugins/statusorbs/StatusOrbsOverlay.java
statusorbs/statusorbs.gradle.kts

statusorbs: option for run orb text

statusorbs: option for run orb text

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

mes: hide destroy for open sack/bag variants

mes: hide destroy for open sack/bag variants

---

randomevents/randomevents.gradle.kts
randomevents/src/main/java/net/runelite/client/plugins/randomevents/RandomEventConfig.java
randomevents/src/main/java/net/runelite/client/plugins/randomevents/RandomEventPlugin.java

randomevents: add dr jekyll notification support

randomevents: add dr jekyll notification support

---

gpu/gpu.gradle.kts
gpu/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java

gpu: unhide computer shaders and add a warning.

gpu: unhide computer shaders and add a warning.

---

antidrag/antidrag.gradle.kts
antidrag/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java
antidrag/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java

fix antidrag in bank
fix antidrag in bank inventory
fix antidrag config valuers only setting when "always on"
split out bank and drag delays

antidrag: various fixes

---

barbarianassault/barbarianassault.gradle.kts
barbarianassault/src/main/java/net/runelite/client/plugins/barbarianassault/Healer.java

Changed heal codes to be in-line with Overstocking method. Healer Death time as follows
W1 28s
W2 30s
W3 40-45s
W4 42s
W5 54s
W6 60s
W7 78s
W8 78s
W9 90/93s
W10 84s

barbarianassault: Updated Heal Codes

---

screenshot/screenshot.gradle.kts
screenshot/src/main/java/net/runelite/client/plugins/screenshot/PvPKillScreenshotMode.java
screenshot/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java
screenshot/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java

depends on https://github.com/open-osrs/runelite/pull/2507
will fail builds until that gets merged

screenshot: add config for feature update and add option to screenshot pvp kills on enemy death 

---

gpu/gpu.gradle.kts
gpu/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
gpu/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java
gpu/src/main/java/net/runelite/client/plugins/gpu/config/WindowsScalingMode.java

Mirror finally works with the GPU plugin.  
Stretched Mode works with gpu mirror as well 🙏   
Hope you guys enjoy the actual release of Mirror :p

gpu: add support for mirror

---

gpu/gpu.gradle.kts
gpu/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
mirror/mirror.gradle.kts
mirror/src/main/java/net/runelite/client/plugins/mirror/MirrorPlugin.java

This updates the Mirror and GPU plugins to ensure that performance isn't hurt unless you are actually using the mirror plugin.

mirror: update plugins to use api

---

loottracker/loottracker.gradle.kts
tmorph/tmorph.gradle.kts

This is an auto-generated PR with updated gradle dependencies

project: Update gradle dependencies

---

kingdomofmiscellania/kingdomofmiscellania.gradle.kts
kingdomofmiscellania/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomPlugin.java

kingdom: fix infobox

---

experiencedrop/experiencedrop.gradle.kts
experiencedrop/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java

xpdrops: add support for new dmm xp rates

xpdrops: add support for new dmm xp rates

---

profiles/profiles.gradle.kts
profiles/src/main/java/net/runelite/client/plugins/profiles/ProfilesPlugin.java

at least that's what I was aiming for

Profiles: Make ProfilePlugin.onConfigChanged not throw anything

---

experiencedrop/experiencedrop.gradle.kts
experiencedrop/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java

expdrops: fix w45 DMM damage drop

expdrops: fix w45 DMM damage drop

---

raids/raids.gradle.kts
raids/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java

raids: fix points chat message

raids: fix points chat message

---

raids/raids.gradle.kts
raids/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java

now handles the following:
Congratulations - your raid is complete!
Team size: 6 players Duration: 4:20 Personal best: 4:03
Congratulations - your raid is complete!
Team size: Solo Duration: 44:44 Personal best: 44:43
Congratulations - your raid is complete!
Team size: 15-23 players Duration: 44:44 Personal best: 44:43

raids: regex fix

---

raids/raids.gradle.kts
raids/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java

Fix regex for new format and to check personal best regex
Fix matcher to check correct group
Split builder into separate method so there isn't duplicated code or need for 2 regex matchers

CoxScouter: Fix Cox points chat message

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

I accidentally click on trees a lot.

menuentryswapper: Deprioritize chop down

---

chathistory/chathistory.gradle.kts
chathistory/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java
chathistory/src/main/java/net/runelite/client/plugins/chathistory/ChatboxTab.java

chathistory: fix

---

bronzeman/bronzeman.gradle.kts
bronzeman/src/main/java/net/runelite/client/plugins/bronzeman/BronzeManPlugin.java

bronzemanmode: fix

---

cluescroll/cluescroll.gradle.kts
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollEmoteOverlay.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollMusicOverlay.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollOverlay.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollServiceImpl.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollWorldMapPoint.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollWorldOverlay.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/ThreeStepCrypticClue.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/item/AllRequirementsCollection.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/item/AnyRequirementCollection.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/item/MultipleOfItemRequirement.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/item/RangeItemRequirement.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/item/SingleItemRequirement.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/item/SlotLimitationRequirement.java

cluescroll: fix cluescroll plugin

cluescroll: fix cluescroll plugin

---

cluescroll/cluescroll.gradle.kts
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
cluescroll/src/main/java/net/runelite/client/plugins/cluescrolls/clues/ThreeStepCrypticClue.java

removed developermode, added back accesslevel for getters.

cluescroll: fix

---

build.gradle.kts

This reverts commit 42e81dc434e2a529fa6e7378aff702f80816cf52.

radiance: Revert update

---

menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/util/CustomSwapParse.java
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/util/DepositMode.java
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/util/WithdrawMode.java

mes: shift/withdraw hotkey options

mes: shift/withdraw hotkey options

---

raidsthieving/raidsthieving.gradle.kts
raidsthieving/src/main/java/net/runelite/client/plugins/raidsthieving/BatsLocatorPlugin.java

raidsthieving: fix raids bat locator not working

raidsthieving: fix raids bat locator not working

---

devtools/devtools.gradle.kts
devtools/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java
devtools/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java
devtools/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java

Requires open-osrs/runelite#2658
Adds extra debug information for players to dev tools, specifically movement-based animations.
https://i.imgur.com/aOswWLN.png

devtools: add extended player debug info

---

slayermusiq/slayermusiq.gradle.kts
slayermusiq/src/main/java/net/runelite/client/plugins/slayermusiq/QuestGuideLinks.java

Added a link for the Sins of the father quest guide to the Slayermusiq1 list.

slayermusiq: Added Sins of the father video link

---

screenshot/screenshot.gradle.kts
screenshot/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java
screenshot/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java

screenshot: screenshot second tradescreen

---

reportbutton/reportbutton.gradle.kts
reportbutton/src/main/java/net/runelite/client/plugins/reportbutton/ReportButtonPlugin.java
reportbutton/src/main/java/net/runelite/client/plugins/reportbutton/TimeStyle.java

Add membership days remaining to the report button plugin as per the suggestion made in #324.

Reportbutton: add membership days remaining to the report button plugin

---

raids/raids.gradle.kts
raids/src/main/java/net/runelite/client/plugins/raids/Parse.java

raids: Fix raids room white/blacklist parse class

---

grounditems/grounditems.gradle.kts
grounditems/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java

depends on open-osrs/runelite#2716

Grounditems: Enable alpha text component

---

experiencedrop/experiencedrop.gradle.kts
experiencedrop/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java

xpdrops: upstream fix

---

friendnotes/friendnotes.gradle.kts
friendnotes/src/main/java/net/runelite/client/plugins/friendnotes/FriendNoteOverlay.java
friendnotes/src/main/java/net/runelite/client/plugins/friendnotes/FriendNotesPlugin.java

friendnotes: fix mouse hovered overlay

friendnotes: fix mouse hovered overlay

---

corp/corp.gradle.kts
corp/src/main/java/net/runelite/client/plugins/corp/CorpConfig.java
corp/src/main/java/net/runelite/client/plugins/corp/CorpPlugin.java

corp: Compliance

---

raids/raids.gradle.kts
raids/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java

raids: reduce unneeded log spam

raids: reduce unneeded log spam

---

build.gradle.kts
buildSrc/build.gradle.kts
highscore/highscore.gradle.kts
loottracker/loottracker.gradle.kts
tmorph/tmorph.gradle.kts

This is an auto-generated PR with an updated gradle dependencies

gradle: Update gradle dependencies

---

settings.gradle.kts
slayer/slayer.gradle.kts
slayer/src/main/java/net/runelite/client/plugins/slayer/Task.java

A fix for this error:
My first pr, please let me know if I have done something incorrectly.

slayer: npe fix

---

attackstyles/attackstyles.gradle.kts
attackstyles/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java

shared and autocast/def styles weren't being hidden.

attackstyle: fix styles not being hidden

---

skillcalculator/skillcalculator.gradle.kts
skillcalculator/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_runecraft.json

skillcalc: adding missing Daeyalt essence bonuses

---

classic-377/classic-377.gradle.kts
classic-377/src/main/java/com/openosrs/classic377/RSClassic377Plugin.java

kids keep pestering them for support, of course.

classic377: remove apollo discord link

---

menuentryswapper/menuentryswapper.gradle.kts
menuentryswapper/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

fixes deprioritizing house ad and chopdown
thanks tom c and gabon

MES: Fix deprioritize house ad and chopdown

---

npchighlight/npchighlight.gradle.kts
npchighlight/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java

Why was this if condition even reversed?

npchighlight: Fix Tag-all options statement

---

equipmentinspector/equipmentinspector.gradle.kts
equipmentinspector/src/main/java/net/runelite/client/plugins/equipmentinspector/EquipmentInspectorPlugin.java

As @Ganom pointed out, I'm dumb asf.
Fixes #473 ...

equipmentinspector: Fix inspector

---

equipmentinspector/equipmentinspector.gradle.kts
equipmentinspector/src/main/java/net/runelite/client/plugins/equipmentinspector/EquipmentInspectorConfig.java

equipmentinspector: protect 0

---

metronome/metronome.gradle.kts
metronome/src/main/java/net/runelite/client/plugins/metronome/MetronomePlugin.java
music/music.gradle.kts
music/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java

project: fix build

---

zalcano/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoPlugin.java
zalcano/zalcano.gradle.kts

project: fix zalcano

---

equipmentinspector/equipmentinspector.gradle.kts
equipmentinspector/src/main/java/net/runelite/client/plugins/equipmentinspector/EquipmentInspectorPlugin.java

Have a look at the pull request for OpenOSRS: https://github.com/open-osrs/runelite/pull/2876
If that pull request is accepted, thise one should be used aswell.

EquipmentInspector: Fix it so multiple plugins can compare appearance

---

buildSrc/src/main/kotlin/Dependencies.kt
grounditemsextended/grounditemsextended.gradle.kts
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/GroundItemExtended.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/GroundItemExtendedInputListener.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/GroundItemsExtendedConfig.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/GroundItemsExtendedOverlay.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/GroundItemsExtendedPlugin.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/ItemThreshold.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/LootType.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/MenuEntryWithCount.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/NamedQuantity.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/WildcardMatchLoader.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/config/HighlightTier.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/config/ItemHighlightMode.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/config/MenuHighlightMode.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/config/PriceDisplayMode.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/config/TimerDisplayMode.java
grounditemsextended/src/main/java/net/runelite/client/plugins/grounditemsextended/config/ValueCalculationMode.java

grounditemsextended: bring back the OG
old ground items....

grounditemsextended: bring back the OG

---

buildSrc/src/main/kotlin/Dependencies.kt
grounditemsextended/grounditemsextended.gradle.kts
settings.gradle.kts

project: fix and version

---

buildSrc/src/main/kotlin/Dependencies.kt
playerindicatorsextended/playerindicatorsextended.gradle.kts
playerindicatorsextended/src/main/java/net/runelite/client/plugins/playerindicatorsextended/PlayerIndicatorsExtendedOverlay.java
playerindicatorsextended/src/main/java/net/runelite/client/plugins/playerindicatorsextended/PlayerIndicatorsExtendedPlugin.java

project: 4.7.1 compatibility

---

betterprofiles/betterprofiles.gradle.kts
betterprofiles/src/main/java/net/runelite/client/plugins/betterprofiles/BetterProfilePanel.java

betterprofiles: keep working if you cancel auth screen

---

buildSrc/src/main/kotlin/Dependencies.kt
grounditemsextended/grounditemsextended.gradle.kts

grounditems: bump

---

buildSrc/src/main/kotlin/Dependencies.kt

"It's like this whole project is outdated..."

project: bump
